services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: notes
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - database
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
      timeout: 20s
      retries: 10
  server:
    build:
      context: ./server
      args: 
        - DEV=true
    networks:
      - database
    depends_on:
      mysql:
        condition: service_healthy 
    ports:
     - "8000:8000"
    volumes:
      - ./server:/server
    command:
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: mysql
      DB_NAME: notes
      DB_USER: root
      DB_PASS: admin
      DB_PORT: 3306
    restart: always

networks:
  database:
    driver: bridge
volumes:
    mysql-data: